[package]
name = "cr7c"
version = "0.1.0"
authors = ["dejavudwh <494319000@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
