[package]
name = "cr7c"
version = "0.1.0"
authors = ["dejavudwh"]
edition = "2018"

[workspace]
members = [
    "lex",
    "parse",
    "analysis",
    "ir",
]

[dependencies]
lex = { path = "./lex" }
parse = { path = "./parse" }
analysis = { path = "./analysis" }
ir = { path = "./ir" }